### PR TITLE
remove repo url override and enable repo.

### PR DESCRIPTION
**Pull request by annakrystalli**
An override of the repo url was being applied, I think only so that the repo would be enabled, which seems out of date and was interfering with automatic package updates (https://github.com/INSIGNEO/redcap_ansible/issues/81). 

Here I've
- removed the code that resulted in overriding of the base url
- added a step to enable the default repo by tweaking the settings in the repo config file using [`community.general.ini_file`](https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html#ansible-collections-community-general-ini-file-module) (as suggested in the [`yum_repository_module` docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html#synopsis) for updating an existing repository definition.

### CODE REVIEW

**Comment by willfurnass** [comment]
Not working for me with Vagrant:
```
TASK [rsesheffield.php : include_tasks] ****************************************
fatal: [vagrant-web1]: FAILED! => {"reason": "couldn't resolve module/action 'community.general.ini_file'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/vagrant/roles/rsesheffield.php/tasks/setup-RedHat.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable PHP repo so we get upgrades\n  ^ here\n"}
```

despite me already having run `ansible-galaxy collection install community.general`.

**Comment by annakrystalli** [comment]
Are you sure you're not using an ansible environment where it's not installed? if you are using a vagrant ansible box you will need to install it on there too.

**Comment by annakrystalli** [comment]
It's definitely a problem with having that collection installed properly. I'm using my system ansible where it is installed and it works fine.

**Comment by annakrystalli** [comment]
What do you get if you run 
`ansible-galaxy collection list`?

**Comment by willfurnass** [comment]
Ah, it's installed locally but possibly not in the `vagrant-ansible1` VM (which I've just deleted and need to recreate).  I'll bring up another `vagrant-ansible1` instance and check what collections are installed post-provisioning.

**Comment by willfurnass** [comment]
Solution to my issue: update `requirements.yml` (in the `redcap-ansible` repo) so it installs the required collection on the `vagrant-ansible1` VM:

```yaml
---
collections:
- my_namespace.my_collection

roles:
  # Install Ansible roles from the Galaxy repository
  - src: geerlingguy.repo-epel
  ...
```

**Comment by annakrystalli** [comment]
Great! And yes I've got these updates lined up in https://github.com/INSIGNEO/redcap_ansible/, just been waiting to merge this so I can use this updated role there too.

I'm assuming it all worked ok and that there isn't something obviously silly in the PR so given I've tested it out too on the dev server I'll go ahead and merge. Thanks for the help @willfurnass !

**Comment by annakrystalli** [comment]
Actually, @willfurnass  one last sanity check. The fact that there is a space before and after the `=` when I enable the repo through `community.general.ini_file` is not a problem right? 👇

```
 [remi-php73]
name=Remi's PHP 7.3 RPM repository for Enterprise Linux 7 - $basearch
#baseurl=http://rpms.remirepo.net/enterprise/7/php73/$basearch/
#mirrorlist=https://rpms.remirepo.net/enterprise/7/php73/httpsmirror
mirrorlist=http://cdn.remirepo.net/enterprise/7/php73/mirror
enabled = 1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
```

It doesn't cause an error when I run `sudo yum -y update --exclude= --skip-broken` so I'm assuming it's all ok.

**Comment by willfurnass** [comment]
Don't think whitespace matters; from https://en.wikipedia.org/wiki/INI_file#Keys_(properties): 
> 
> Leading and trailing whitespaces around the outside of the property name are ignored.

**Comment by willfurnass** [comment]
Huh, I lied: still getting:
```
fatal: [vagrant-web1]: FAILED! => {"reason": "couldn't resolve module/action 'community.general.ini_file'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/vagrant/roles/rsesheffield.php/tasks/setup-RedHat.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable PHP repo so we get upgrades\n  ^ here\n"}
```
when trying to provision via `vagrant-ansible1`

**Comment by annakrystalli** [comment]
Did you destroy the ansible vagrant box? If so you will likely need to reinstall the collection manually. This is the problem I was having with the ansible box for xnat when I was trying to install the xml processing collection. I just could not find a way to automate collection installation through vagrant. It never seemed to install properly through the `requirements.yml`.

In any case it has worked for me successfully on the dev and now live box too. 😊

**Comment by willfurnass** [comment]
Yeah, I did destroy it but hoped my modifications to `requirements.yml` would ensure the collection was automatically installed. Confused.

**Comment by annakrystalli** [comment]
It's super confusing!! I tried for ages to solve it for xnat and ended up just giving up cause it made no sense to me! The closest I got was that I think they weren't getting installed where they do when you install manually as the vagrant command uses sudo...or at least that was my diagnosis. But I couldn't figure out how to circumvent it.

**Pull request merged**
